[package]
name = 'kuriero'
version = '0.1.0'
edition = '2024'

[dependencies]
serde = { version = '1.0.229', features = ['derive'] }
serde_json = '1.0.151'
ureq = { version = '3.4.2', default-features = false, features = ['json'] }

[features]
default = ['rustls']
rustls = ['ureq/rustls']

[lints.rust]
warnings = 'deny'

[lints.clippy]
pedantic = { level = 'warn', priority = -1 }
